from core.config import (
    CHAT_STRATEGY,
    CHAT_QUALITY,
    CHAT_ECONOMY,
    CHAT_INTL_BUSINESS,
)

SCHEDULE = {
    "monday": [
        {
            "pair": 1,
            "subject": "Качество и безопасность в гостиничной деятельности",
            "type": "lecture",
            "weeks": range(4, 9),
            "room": "2/214",
            "teacher": "Махмудова А.П.",
            "chat_id": CHAT_QUALITY,
        },
        {
            "pair": 1,
            "subject": "Стратегический менеджмент в гостиничном хозяйстве",
            "type": "lecture",
            "weeks": range(10, 16),
            "room": "2/214",
            "teacher": "Усманова Н.М.",
            "chat_id": CHAT_STRATEGY,
        },
        {
            "pair": 2,
            "subject": "Стратегический менеджмент в гостиничном хозяйстве",
            "type": "lecture",
            "weeks": range(4, 9),
            "room": "2/214",
            "teacher": "Усманова Н.М.",
            "chat_id": CHAT_STRATEGY,
        },
        {
            "pair": 2,
            "subject": "Мировая экономика и МЭО",
            "type": "lecture",
            "weeks": range(10, 16),
            "room": "2/214",
            "teacher": "Халимов Ш.Х.",
            "chat_id": CHAT_ECONOMY,
        },
        {
            "pair": 3,
            "subject": "Урок просвещения",
            "type": "lecture",
            "weeks": range(4, 16),
            "room": "3/305",
            "teacher": "—",
            "chat_id": CHAT_STRATEGY,
        },
    ],

    "tuesday": [
        {
            "pair": 1,
            "subject": "Мировая экономика и МЭО",
            "type": "lecture",
            "weeks": range(4, 11),
            "room": "2/214",
            "teacher": "Халимов Ш.Х.",
            "chat_id": CHAT_ECONOMY,
        },
        {
            "pair": 1,
            "subject": "Мировая экономика и МЭО",
            "type": "seminar",
            "weeks": range(11, 16),
            "room": "2/214",
            "teacher": "Амриева Ш.Ш.",
            "chat_id": CHAT_ECONOMY,
        },
        {
            "pair": 2,
            "subject": "Качество и безопасность в гостиничной деятельности",
            "type": "lecture",
            "weeks": range(4, 16),
            "room": "2/214",
            "teacher": "Махмудова А.П.",
            "chat_id": CHAT_QUALITY,
        },
        {
            "pair": 3,
            "subject": "Международный гостиничный бизнес",
            "type": "lecture",
            "weeks": range(4, 15),
            "room": "2/214",
            "teacher": "Амриддинова Р.С.",
            "chat_id": CHAT_INTL_BUSINESS,
        },
    ],

    "wednesday": [
        {
            "pair": 1,
            "subject": "Международный гостиничный бизнес",
            "type": "seminar",
            "weeks": range(4, 16),
            "room": "2/214",
            "teacher": "Мейлиев А.Н.",
            "chat_id": CHAT_INTL_BUSINESS,
        },
        {
            "pair": 2,
            "subject": "Качество и безопасность в гостиничной деятельности",
            "type": "seminar",
            "weeks": range(4, 16),
            "room": "2/214",
            "teacher": "Мир-Джафарова А.Д.",
            "chat_id": CHAT_QUALITY,
        },
        {
            "pair": 3,
            "subject": "Стратегический менеджмент",
            "type": "lecture",
            "weeks": [10],
            "room": "2/214",
            "teacher": "Усманова Н.М.",
            "chat_id": CHAT_STRATEGY,
        },
        {
            "pair": 3,
            "subject": "Мировая экономика",
            "type": "seminar",
            "weeks": [15],
            "room": "2/214",
            "teacher": "Амриева Ш.Ш.",
            "chat_id": CHAT_ECONOMY,
        },
    ],

    "thursday": [
        {
            "pair": 1,
            "subject": "Мировая экономика",
            "type": "seminar",
            "weeks": range(4, 16),
            "room": "2/214",
            "teacher": "Амриева Ш.Ш.",
            "chat_id": CHAT_ECONOMY,
        },
        {
            "pair": 2,
            "subject": "Стратегический менеджмент",
            "type": "lecture",
            "weeks": range(4, 10),
            "room": "2/214",
            "teacher": "Усманова Н.М.",
            "chat_id": CHAT_STRATEGY,
        },
        {
            "pair": 2,
            "subject": "Международный гостиничный бизнес",
            "type": "seminar",
            "weeks": [10],
            "room": "2/214",
            "teacher": "Мейлиев А.Н.",
            "chat_id": CHAT_INTL_BUSINESS,
        },
        {
            "pair": 2,
            "subject": "Качество и безопасность",
            "type": "seminar",
            "weeks": range(11, 16),
            "room": "2/214",
            "teacher": "Мир-Джафарова А.Д.",
            "chat_id": CHAT_QUALITY,
        },
        {
            "pair": 3,
            "subject": "Стратегический менеджмент",
            "type": "seminar",
            "weeks": range(6, 13),
            "room": "2/214",
            "teacher": "Бурхонова Н.М.",
            "chat_id": CHAT_STRATEGY,
        },
    ],

    "friday": [
        {
            "pair": 1,
            "subject": "Стратегический менеджмент",
            "type": "seminar",
            "weeks": range(4, 10),
            "room": "2/214",
            "teacher": "Бурхонова Н.М.",
            "chat_id": CHAT_STRATEGY,
        },
        {
            "pair": 1,
            "subject": "Международный гостиничный бизнес",
            "type": "seminar",
            "weeks": range(11, 16),
            "room": "2/214",
            "teacher": "Мейлиев А.Н.",
            "chat_id": CHAT_INTL_BUSINESS,
        },
        {
            "pair": 2,
            "subject": "Мировая экономика",
            "type": "lecture",
            "weeks": range(4, 9),
            "room": "2/214",
            "teacher": "Халимов Ш.Х.",
            "chat_id": CHAT_ECONOMY,
        },
        {
            "pair": 2,
            "subject": "Качество и безопасность",
            "type": "lecture",
            "weeks": [9],
            "room": "3/207",
            "teacher": "Махмудова А.П.",
            "chat_id": CHAT_QUALITY,
        },
        {
            "pair": 3,
            "subject": "Международный гостиничный бизнес",
            "type": "lecture",
            "weeks": range(4, 10),
            "room": "2/214",
            "teacher": "Амриддинова Р.С.",
            "chat_id": CHAT_INTL_BUSINESS,
        },
    ],
}